In [2]:
"""
1: Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.
"""

import numpy  as np

list1 = [5,7,9]
def myvander(seq,increasing="False"):
    if increasing == "False":
        arr = np.empty((0,seq.size),int)
        for i in range(seq.size):
            #print (np.power(seq,seq.size-i-1))
            arr=np.concatenate((arr,np.power(seq,seq.size-i-1).reshape(1,seq.size)),axis=0)
        return arr.T
result_arr = myvander(np.array(list1),"False")
print (result_arr)

[[25  5  1]
 [49  7  1]
 [81  9  1]]


In [6]:
""" Problem Statement 2: Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the 
given sequence is defined as follows: The moving average sequence has n-k+1 elements as shown below. The moving averages with k=4 of a ten-value sequence (n=10) is shown below i 1 2 3 4 5 6 7 8 9 10 ===== == == == == == == == == == == Input 10 20 30 40 50 60 70 80 90 100 y1 25 = (10+20+30+40)/4 y2 35 = (20+30+40+50)/4 y3 45 = (30+40+50+60)/4 y4 55 = (40+50+60+70)/4 y5 65 = (50+60+70+80)/4 y6 75 = (60+70+80+90)/4 y7 85 = (70+80+90+100)/4 Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. """

seq = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3

def movingAverage(seq,window):
    np.average
    for i in range(0,(len(seq)-k+1)):
        seq_arr = np.array(seq)
        print ("Moving average {} of y{} is {}".format(seq_arr[i:i+k],i,np.average(seq_arr[i:i+k])))
    
movingAverage(seq,k)

Moving average [3 5 7] of y0 is 5.0
Moving average [5 7 2] of y1 is 4.666666666666667
Moving average [7 2 8] of y2 is 5.666666666666667
Moving average [ 2  8 10] of y3 is 6.666666666666667
Moving average [ 8 10 11] of y4 is 9.666666666666666
Moving average [10 11 65] of y5 is 28.666666666666668
Moving average [11 65 72] of y6 is 49.333333333333336
Moving average [65 72 81] of y7 is 72.66666666666667
Moving average [72 81 99] of y8 is 84.0
Moving average [ 81  99 100] of y9 is 93.33333333333333
Moving average [ 99 100 150] of y10 is 116.33333333333333


In [ ]:
"""
Assignment 6 completed
"""